pipeline:
  name: Hello World
  identifier: Hello_World
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: CI Test
        identifier: CI_Test
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: VM
            spec:
              type: Local
              spec:
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Test
                  identifier: Echo_Test
                  spec:
                    shell: Sh
                    command: echo "hello world"
